---
- name: Delete Kolla Nodes
  hosts: all
  user: root
  ignore_errors: true

  tasks:
  - include_role:
      name: delete_nodes
  - include_role:
      name: libvirt_network
      tasks_from: delete.yml
    vars:
      libvirt_network_name: "{{ item  }}"
    with_items:
    - "{{ network_ssh }}"
    - "{{ network_openstack }}"
    - "{{ network_neutron }}"
    when: create_networks
