#################
# EXAMPLE FILE  #
#################

###############################################################
#  !!!WARNING!!!: DO NOT USE WITHOUT EDITING FIRST             #
#  It's recommended to copy this config to user/ subdirectory #
###############################################################


## KOLLA IMAGES
# Directory where the disk images will be located
# default is the libvirt image pool
# make sure you have enough disk space on the partition
# if not then change to something on your /home
image_pool: "/var/lib/libvirt/images"

# Path to the base node image
image_path: "{{ image_pool }}/kolla-image.qcow2"


## REMOTE HOST
# If you are running libvirt on remote host
is_remote: false
# Image pool on remote host
remote_image_pool: "/var/lib/libvirt/images"

# SSH key for the remote host
proxy_server_private_key: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_rsa"


## NETWORK


# Name for libvirt ssh network. Must be unique, no network with such name should be defined
network_ssh: "kolla-ssh"

# Bridge for ssh network. The bridge must not be in use
network_ssh_bridge: virbr1

# Ip of the ssh network. All IP configuration is generated from this
network_ssh_ip: "192.168.100.0"

# If you want to configure IP adresses manually (not reccomended)
# # Start of the SSH netwotk ip range
# network_ssh_ip_start: 192.168.100.2
# # End of the SSH netwotk ip range
# network_ssh_ip_end: 192.168.100.254
# # Gateway (host machine) of the SSH network
# network_ssh_ip_gateway: 192.168.100.1
# # SSH network CIDR
# network_ssh_ip_range: 192.168.100.0/24

# Name for libvirt Openstack network. Must be unique, no network with such name should be defined
network_openstack: "kolla-openstack"

# Bridge for Openstack network. The bridge must not be in use
network_openstack_bridge: virbr2

# Ip of the Openstack network. All IP configuration is generated from this
network_openstack_ip: "192.168.123.0"

# If you want to configure IP adresses manually, do it according to network_ssh examples replacing prefix with network_openstack

# Name for libvirt Neutron network. Must be unique, no network with such name should be defined
network_neutron: "kolla-neutron"

# Bridge for Openstack network. The bridge must not be in use
network_neutron_bridge: virbr3

# Ip of the ssh network. All IP configuration is generated from this
network_neutron_ip: "192.168.124.0"

# If you want to configure IP adresses manually, do it according to network_ssh examples replacing prefix with network_neutron

# Whether create networks, disable this if you already have 3 networks, e.g. from previous versions of Kolla Builder
create_networks: true

## GIT PATCH
# Kolla builder can rebase git branches
# Usefull if you have a patch that's  divided into more branches
# Apply git patches
git_patch_kolla: false

# The branch to apply patches to
git_branch: "master"

# The patches applyied using git rebase
git_patches: []


## SSH
# Absolute path to the ssh key
# Either copy key from ssh/id_kolla to your .ssh directory
# or modify this config to point to ssh/id_kolla
kolla_ssh_key: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_kolla"

# Add nodes to your ssh config
# this way you can easily ssh into nodes by
# ssh -F <ssh_config> <node-name>
# You can change this to .ssh/config for simpler deployment
ssh_config: "ssh_config"


## KOLLA CONFIGURATION
# The VIP address of Kolla ansible, templates the kolla-ansible variable of the same name
# Must be an unused IP of network_openstack_ip subnet
kolla_internal_vip_address: "192.168.123.200"

# globals file (located in kolla-files) subdirectory
# this is usefull if you have several deployment scenarios
# i.e. you develop on multiple branches at once
# This config overrides globals.yml, but does not override kolla_internal_vip_address, which
# is configured separately
# globals_file: user_globals/globals.yml

# Path to kolla-ansible source code
kolla_source_local_path: "./kolla-ansible"


## ADDITIONAL UPLOADS
## Additional Uploads, such as mounted source codes
## This is an experimental feature, works only for aio deployment for now

# Additional uploads path on nodes
additional_upload_node_path: "/home/kolla"

# Mode (recommended to be 0777 if you plan to mount it to containers using `default_extra_mounts`)
additional_upload_mode: "0777"

# List of additional directories to upload
additional_uploads: []

# Additional directiories to be uploaded to deploy node only
# NOTE: This has effect only in multinode setup
additional_uploads_deploy_node: []

## REVERSE PROXY (REMOTE HOST ONLY)

# Openstack services to forward reverse proxy to
# 80 and 443 Are added automaticaly
# Go to http(s)://floating-ip-of-your-remote to access Horizon UI
reverse_proxy_vip_ports_openstack: []

# Non-openstack services, that normally should not be accessible from outside
# Format:
# - ip: ...
#   port: ...
#   ssl: ... (no default value you must specify true/false)
reverse_proxy_additional_servers: []


## ALL-IN-ONE SETUP
# WARNING! delete this section if your setup is multinode
# Whether this setup is for all-in-one deployment
# keep `true` for aio
is_aio: true
# Name of the node
name: "openstack-aio"
# # Recommended resources for the node
ram_size: 10000
# use max available cpus
cpu_count: 12
disk_size: 50


## MULTINODE SETUP
# WARNING! delete this section if your setup is multinode
# Uncomment for multinode setup
# is_aio: false
# Deafult number of CPU allocated to each node
# it's recommended to allocate max CPUs
default_cpu: 12
# Default RAM for each node
# Minimal 1GB RAM to boot the image
default_ram: 1024
# Default RAM for each node
# Minimal 25GB to boot the image
default_disksize: 25

# # Node configuration
# each node can be of different type
#   control: for openstack control plane components
#   network: for openstack networking services
#   compute: openstack compute host
#   storage: for storage services
#   monitoring: for monitoring services
#   deployment: for running kolla-ansible itself, not part of openstack
# You need exactly one deployment and at least one workload (everything else) node
# You have to have the deploy node separated from everything else
# unless you deploy in aio mode, in which case use different config
# file (TODO)
# You can edit ram_size disk_size and cpu_count for each node

# 4+1 node example (3 compute nodes, one control node, one deployment node)
# You can add more if you wish, or create dedicated network nodes for example
nodes:

# # Controll node
# Hosts everything that is not compute

  - name: "openstack-control"
    control: true
    storage: true
    monitoring: true
    network: true
# false is the default option for each node type
    compute: false
#  minimum ram for this node
    ram_size: 8192
    disk_size: 25
#   cpu_count: 12

# # Compute  nodes
# For compute instances
  - name: "openstack-compute-01"
    compute: true
    ram_size: 4096

  - name: "openstack-compute-02"
    compute: true
    ram_size: 4096

  - name: "openstack-compute-03"
    compute: true
    ram_size: 4096

# # Deployment node
# SSH into this node and run kolla
  - name: "openstack-deployment"
    deployment: true
    ram_size: 1024
