---
- name: Wait for hosts to be avialable
  hosts: all
  user: root
  vars:
    ansible_ssh_common_args: '-o IdentitiesOnly=yes'
  tasks:
    - wait_for_connection:
        timeout: "{{ ssh_connection_timeout }}"

- name: Prepare Kolla Nodes
  hosts: all
  user: root
  gather_facts: true
  vars:
    ansible_ssh_common_args: '-o IdentitiesOnly=yes'
  tasks:
    - name: Prepare nodes for Kolla deployment
      include_role:
        name: prepare_nodes

    - name: Upload Additional files to nodes
      include_role:
        name: upload_to_nodes
      vars:
        source_local_path: "{{ item }}"
        source_node_path: "{{ additional_upload_node_path ~ '/' ~ item.split('/')[-1] }}"
      with_items: "{{ additional_uploads }}"

- name: Prepare deployment Node
  hosts: deployment
  user: root
  vars:
    ansible_ssh_common_args: '-o IdentitiesOnly=yes'
  roles:
    - name: git_patch
      delegate_to: localhost
      when: git_patch_kolla

  tasks:
    - name: Prepare deployment node for Kolla deployment
      include_role:
        name: upload_to_nodes
    - name: Upload Kolla Ansible
      include_role:
        name: "upload_archive"
      vars:
        source_local_path: "{{  patched_git_repo if git_patch_kolla else kolla_source_local_path }}"
        source_node_path: "{{ kolla_source_node_path }}"
    - name: Upload Additional files to Deployment node
      include_role:
        name: "upload_archive"
      vars:
        source_local_path: "{{ item }}"
        source_node_path: "{{ additional_upload_node_path ~ '/' ~ item.split('/')[-1] }}"
      with_items: "{{ additional_uploads_deploy_node }}"

- name: Configure ARA recording on deployment Node
  hosts: deployment
  become: false
  vars:
    ansible_ssh_common_args: '-o IdentitiesOnly=yes'

  pre_tasks:
    - name: Get control IP data
      ansible.builtin.shell:
        cmd: 'who | cut -d "(" -f2 | cut -d ")" -f1'
      changed_when: false
      check_mode: false
      register: host_ip_data
      when: ara_enable | bool

    - name: Extract host IP from data
      ansible.builtin.set_fact:
        host_ip: "{{ host_ip_data.stdout_lines[0] }}"
      when: ara_enable | bool
  roles:
    - role: config_ara_recording
      become: true
      become_user: kolla
      vars:
        ara_server_ip: "{{ host_ip }}"
        config_to_edit: "~/ansible.cfg"
        python_bin_path: "/home/kolla/kolla/bin/"
      when: ara_enable | bool
