---
- name: Generate IP addreses
  include_role:
    name: generate_ip

- name: Ensure that the disk image is available on remote_ip
  copy:
    src: "{{ image_path }}"
    dest: "{{ remote_image_path }}"
    force: false
  when: is_remote

- name: Copy disk Image
  shell: |
    cp {{ remote_image_path if is_remote else image_path }} {{ disk_path }}

- name: Resize disk Image to coreect size
  shell: |
    qemu-img resize {{ disk_path }} {{ disk_size }}G

- name: Define a VM
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'kolla-node.xml.j2') }}"

- name: Start a VM
  community.libvirt.virt:
    name: "{{ node_name }}"
    state: running

- name: Ensure ssh config exists
  delegate_to: localhost
  copy:
    content: ""
    dest: "{{ ssh_config }}"
    force: false

- name: Add machine to SSH config
  delegate_to: localhost
  blockinfile:
    marker: "# {mark} {{ node_name | upper }}"
    path: "{{ ssh_config }}"
    block: "{{ lookup('template', 'ssh_config.j2') }}"
